server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

  feign:
    circuitbreaker:

      enabled: true

    client:
      config:
        product-service:

          connectTimeout: 5000

          readTimeout: 5000

          loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      product-service:

        slidingWindowSize: 10

        failureRateThreshold: 50

        waitDurationInOpenState: 10000

        permittedNumberOfCallsInHalfOpenState: 3

        automaticTransitionFromOpenToHalfOpenEnabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
